### ISSUE TITLE
Incorrect dates voor Allerheiligen en Allerzielen

### ISSUE THREAD

**Issue by Marlat24** [PanderMusubi/dutch-holidays#11]
Allerheilgen is always a 1 November
Allerzielen is always at 2 November

You put them incorrectly at 31 December.

**Comment by PanderMusubi** [comment]
Fixed in https://github.com/PanderMusubi/dutch-holidays/commit/5f256492f105fcdc334a62cbeec92da74f4137f1

Forgot to change the first line in the scripted files. Thanks for checking.
