### ISSUE TITLE
Double entries

### ISSUE THREAD

**Issue by Gendji** [PanderMusubi/dutch-holidays#14]
Checking my mail today in Thunderbird, i noticed that all holidays that have the same date every year are showing up double. 

For example today:

Aswoensdag is shown once.
Valentijnsdag is shown two times. As are all other yearly returning events (Internationale Vrouwendag is the next one for example)

Thunderbird version 102.15.1 (Yes still holding on :D)

**Comment by PanderMusubi** [comment]
I have the same problem with Thunderbird 115.6.0 but not via https://f-droid.org/en/packages/at.bitfire.icsdroid/ in https://f-droid.org/en/packages/ws.xsoh.etar/

The problem is indeed only with the scripted holidays (always the same date every year). Looking at the ICS files, I don't see the problem. Do you perhaps? Can it be a caching problem in Thunderbird?

**Comment by PanderMusubi** [comment]
Is a problem with Thunderbird. Remove the network read only calender and add it again and the problem is solved. Please reopen this issue when needed. Perhaps also good to report this at Thunderbir if you would.

**Comment by Gendji** [comment]
It's working again, thank you!.

I would gladly report it at Thunderbird but i do not know what the exact problem is? Or do i just describe what happened and how you found a solution?

**Comment by PanderMusubi** [comment]
You can report it here https://bugzilla.mozilla.org/home

To replicate, a http server should offer in this order with a day in between under the same URL the raw content of:
1. https://github.com/PanderMusubi/dutch-holidays/blob/5f256492f105fcdc334a62cbeec92da74f4137f1/NederlandseFeestdagen.ics
2. https://github.com/PanderMusubi/dutch-holidays/blob/f50442a77c5ef542b43d08b07e3531ce00aac2f0/NederlandseFeestdagen.ics
3. https://github.com/PanderMusubi/dutch-holidays/blob/d5e574ff56affd4c3e3b99c5e98930937e7d84f3/NederlandseFeestdagen.ics

Then after two days days, the duplicates will appear

**Comment by Gendji** [comment]
It seems that the problem is gone now, at least for Dutch Holidays. 

I am using Thunderbird 128.3.3esr at the moment and the problem only occurs for other Calendars i use. But even with those calendars the double entries are gone when i scroll up or down, without using reload and synchronize. So the problem for those calendars is only for the Calendar view that Thunderbird starts with.

(Hope i am making sense :D)

I do not know if you still have this problem but for me the "bug" is gone.

**Comment by PanderMusubi** [comment]
Yeah, this was a Thunderbird issue.
