### ISSUE TITLE
Incorrect date for Good Friday 2022 in Dutch holidays calendars

### ISSUE THREAD

**Issue by Marlat24** [PanderMusubi/dutch-holidays#7]
Please, note that in the Dutch holidays calendars,  in 2022 Good Friday is on 15 April, not on Sunday 27 March.
You may want to correct this. :-)

**Comment by PanderMusubi** [comment]
@Marlat24 , thanks for reporting. Please double check the changes in the .txt files (I found a few more dates that neede fixing) at the bottom of https://github.com/PanderMusubi/dutch-holidays/commit/f0e3158ede5ba016f4eef37cbf98b05bcb346914 and check the .ics files in this repo. Let me know all is okay, then I will also ask Mozilla to update their versions.

**Comment by Marlat24** [comment]
Changes look OK to me!
Thanks for fixing the issue.
