### ISSUE TITLE
Alkmaars Ontzet (Siege of Alkmaar) Date

### ISSUE THREAD

**Issue by Gendji** [PanderMusubi/dutch-holidays#8]
ICS Entry states:

SUMMARY:Alkmaars Ontzet (Siege of Alkmaar)
UID:20220303T074501Z-265889-0001-en@katana
RRULE:FREQ=YEARLY;BYMONTHDAY=1;BYMONTH=8
DTSTART;VALUE=DATE:20100801
DTEND;VALUE=DATE:20100802
ATTACH:https://nl.wikipedia.org/wiki/Alkmaars_Ontzet

Which is the first of August if i am not mistaken?. 

The Holiday however is the 8th of October.

**Comment by PanderMusubi** [comment]
Thanks, fixed in https://github.com/PanderMusubi/dutch-holidays/commit/d1cd322625591e8e3bfd1885139feccc0d8e2582 and in https://github.com/thundernest/thunderbird-website/pull/289
