### ISSUE TITLE
Allerheiligen en Allerzielen

### ISSUE THREAD

**Issue by Marlat24** [PanderMusubi/dutch-holidays#9]
Hoi Pander,

De volgende speciale dagen ontbreken nog in de dutch-holidays kalender:

-) Allerheiligen (altijd op 1 november).
-) Allerzielen (altijd op 2 november.

**Comment by PanderMusubi** [comment]
Fixed in https://github.com/PanderMusubi/dutch-holidays/commit/d07e7ad248e1eaad2161e9e2772199b3493f07c1

**Comment by Marlat24** [comment]
Nope. you added these days but uou got the dates wrong (31/12). See above for the correct dates.

**Comment by PanderMusubi** [comment]
Fixed via https://github.com/PanderMusubi/dutch-holidays/issues/11
